sudo: required
services:
    - docker

before_install:
    - docker build -t docker_react_image -f Dockerfile.dev .


script:
    - docker run docker_react_image npm run test -- --watchAll=false

deploy:
    provider: elasticbeanstalk
    regin: "us-east-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "autocreated by EBS"
    bucket_path: "app_name"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"

        

